spring.application.name=account-service

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/common_local_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Liquibase Settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:liquibase/changelog/changelog-master.xml

# Debugging
logging.level.liquibase=INFO
logging.level.org.springframework.boot.autoconfigure.liquibase=DEBUG